// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Roomly.Data;
using System;

namespace Roomly.Data.Migrations
{
    [DbContext(typeof(RoomlyContext))]
    [Migration("20181013213553_initial-migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Roomly.Data.Entities.Question", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("A");

                    b.Property<string>("Answer");

                    b.Property<string>("B");

                    b.Property<string>("Body");

                    b.Property<string>("C");

                    b.Property<short>("Category");

                    b.Property<string>("D");

                    b.Property<string>("E");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("MultipleChoice");

                    b.Property<bool>("ShortAnswer");

                    b.Property<string>("Title");

                    b.Property<bool>("TrueFalse");

                    b.HasKey("QuestionId");

                    b.ToTable("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
